import os
import random
import json
from tools.pbs_generator.pbs_parser import PBSFile, PBSSection


def _default_pbs_dir():
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "PBS"))

def generate_random_dungeon_name(theme=None):
    prefixes = ["Mystic", "Shadow", "Crystal", "Forgotten", "Ancient", "Abyssal", "Verdant", "Silent", "Echoing"]
    suffixes = ["Cave", "Ruins", "Depths", "Sanctuary", "Labyrinth", "Hollow", "Grotto", "Chasm"]

    if theme:
        # We can expand these to be more thematic later
        theme_lower = theme.lower()
        if theme_lower == 'grass':
            prefixes = ["Verdant", "Overgrown", "Leafy", "Bramble"]
        elif theme_lower == 'poison':
            prefixes = ["Toxic", "Venomous", "Blighted", "Noxious"]
            suffixes = ["Swamp", "Bog", "Mire", "Sludge"]

    return f"{random.choice(prefixes)} {random.choice(suffixes)}"

def generate_map_metadata(start_id, end_id, theme=None, pbs_dir=None, overwrite=False):
    """
    Mass generates Map Metadata for a range of map IDs, injecting random names,
    the Dungeon flag, and the BGM selected by the Ruby generator.
    """
    if pbs_dir is None:
        pbs_dir = _default_pbs_dir()
    filepath = os.path.join(pbs_dir, "map_metadata.txt")
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"map_metadata.txt not found in PBS folder: {filepath}")
    pbs = PBSFile(filepath)

    # Load BGMs generated by the Ruby script
    map_bgms = {}
    bgm_bridge_path = os.path.join(os.path.dirname(__file__), "map_bgms.json")
    if os.path.exists(bgm_bridge_path):
        try:
            with open(bgm_bridge_path, 'r', encoding='utf-8') as f:
                map_bgms = json.load(f)
        except Exception as e:
            print(f"Warning: Failed to load map_bgms.json: {e}")

    # Load specific map themes generated by the Ruby script
    map_theme_overrides = {}
    theme_bridge_path = os.path.join(os.path.dirname(__file__), "map_themes.json")
    if os.path.exists(theme_bridge_path):
        try:
            with open(theme_bridge_path, 'r', encoding='utf-8') as f:
                map_theme_overrides = json.load(f)
        except Exception as e:
            print(f"Warning: Failed to load map_themes.json: {e}")

    count = 0
    for map_id in range(start_id, end_id + 1):
        header_prefix = f"[{map_id:03d}]"

        if pbs.has_section(header_prefix):
            if overwrite:
                pbs.remove_section(header_prefix)
                print(f"Map {map_id} already exists in map_metadata.txt. Overwriting.")
            else:
                print(f"Map {map_id} already exists in map_metadata.txt. Skipping appending.")
                continue

        # Check if this specific map has a theme override from the tileset name
        map_id_str = str(map_id)
        current_theme = map_theme_overrides.get(map_id_str, theme)

        name = generate_random_dungeon_name(current_theme)

        # Create the new section block
        new_section = PBSSection(f"{header_prefix}   # {name}")
        new_section.add_line(f"Name = {name}")
        new_section.add_line("Dungeon = true")

        # Inject BattleBack and Environment based on theme
        if current_theme:
            theme_capitalized = current_theme.capitalize()
            # Note: We do NOT inject generic Environment names because they must match exact IDs
            # in GameData::Environment (like Grass, Cave, Snow, Ice, Rock, Sand, Forest).
            # "Normal" or generic theme names will crash the compiler.
            # We map known themes to safe environments, else we just assign BattleBack.

            if current_theme.lower() == "ice":
                new_section.add_line("BattleBack = snow")
                new_section.add_line("BattleBase = grassICE")
                # Use Snow for Ice biomes to match the user's graphical preference
                new_section.add_line("Environment = Snow")
            elif current_theme.lower() == "grass":
                new_section.add_line("BattleBack = Grass")
                new_section.add_line("Environment = Grass")
            elif current_theme.lower() in ["water", "poison"]:
                new_section.add_line(f"BattleBack = {theme_capitalized}")
                new_section.add_line("Environment = StillWater")
            else:
                new_section.add_line(f"BattleBack = {theme_capitalized}")
                # Fallback to None to avoid compiler crashes for undefined environments
                new_section.add_line("Environment = None")

        # Inject BGM if available from the Ruby generator
        map_id_str = str(map_id)
        if map_id_str in map_bgms:
            selected_bgm = map_bgms[map_id_str]
            new_section.add_line(f"BGM = {selected_bgm},100,100")

        # Add the separator comment to the previous section or before this one
        if not pbs.sections:
            pbs.preamble.append("#-------------------------------")
        else:
            last_section = pbs.sections[-1]
            if last_section.lines and not last_section.lines[-1].startswith("#-------------------------------"):
                last_section.add_line("#-------------------------------")

        pbs.add_section(new_section)
        count += 1

    if count > 0:
        pbs.save()
        print(f"Generated/Updated Map Metadata for {count} maps.")
    return count
