#===============================================================================
# Procedural Dungeons: Dynamic Event Spawner - Mobile Optimized for v21.1
#===============================================================================
# Hooks into the Overworld_RandomDungeons generation process to randomly spawn
# VIPs, Trainers, and Loot Chests on valid floor tiles.
#===============================================================================

module RoguelikeExtraction
  # Define the Terrain Tags that represent valid floor tiles.
  # Adjust these IDs to match your specific Tileset configuration.
  # Typically 0 is standard passable ground, 1 is ledge, 2 is grass, etc.
  VALID_FLOOR_TERRAIN_TAGS = [:None, :Grass, :TallGrass, :Sand]

  # The Spawner Function
  # Note: Movement/Teleportation is natively handled by Overworld_RandomDungeons.
  # This function strictly assigns dynamic properties (Trainer Classes) and graphics,
  # and scales the total number of events based on the current floor tier.
  # Removes events entirely from the map object so RandomDungeons doesn't process them
  def self.cull_excess_events
    return if !$game_map || !$game_map.events

    floor = $PokemonGlobal.current_raid_floor || 1

    # Scale trainers and chests based on floor assuming a 50-100 floor clear.
    # Floor 1: ~1, Floor 4: ~2, Floor 10: ~3, maxing around 10-12 on very deep floors.
    max_trainers = [[(floor / 5.0).to_i + 1, 10].min, 1].max
    max_chests = [[(floor / 4.0).to_i + 1, 12].min, 1].max

    active_trainers = 0
    active_chests = 0

    events_to_delete = []

    # Iterate through all events on the newly generated map
    $game_map.events.values.each do |event|
      # We identify dynamic entities by their Event Name in RPG Maker
      name = event.name.downcase

      # Handle Trader spawning sparingly (every 5-10 floors)
      # 20% chance if floor > 2, or guaranteed every 5 floors
      if name == "trader"
        should_spawn_trader = (floor % 5 == 0) || (floor > 2 && rand(100) < 20)
        if !should_spawn_trader
          events_to_delete.push(event.id)
          next
        end
      end

      if name.include?("trainer")
        if active_trainers >= max_trainers
          events_to_delete.push(event.id)
          next
        end
        active_trainers += 1
      elsif name.include?("chest")
        if active_chests >= max_chests
          events_to_delete.push(event.id)
          next
        end
        active_chests += 1
      end
    end

    # Actually remove them from the hash so Overworld_RandomDungeons ignores them
    # Note: If called pre-generation, this operates on a temporary Hash, not $game_map.events directly
    events_to_delete.each do |id|
      if $game_map
        $game_map.events.delete(id)
      end
    end

    return events_to_delete
  end

  def self.spawn_dynamic_events
    return if !$game_map || !$game_map.events

    # Iterate through remaining active events
    $game_map.events.values.each do |event|
      name = event.name.downcase

      if name.include?("vip") || name.include?("trainer") || name.include?("chest") || name == "extract" || name == "trader"

        # Pre-calculate Trainer/VIP and apply graphics immediately
        if name.include?("vip") || name.include?("trainer")
          is_vip = name.include?("vip")

          floor = $PokemonGlobal.current_raid_floor || 1
          map_id = $game_map.map_id

          # Version generated by the Python script is floor - 1
          python_version = floor - 1
          python_version = 0 if python_version < 0

          base_name = "M#{map_id}_F#{floor}"
          python_trainer_name = is_vip ? "Boss #{base_name}" : base_name

          # Attempt to find the specific procedurally generated trainer in PBS
          found_key = GameData::Trainer::DATA.keys.find { |k| k[1] == python_trainer_name && k[2] == python_version }

          if found_key
            # The python script generated a trainer explicitly for this floor
            chosen_trainer = [found_key[0], python_trainer_name, python_version]
          else
            # Failsafe fallback to the hardcoded pools if the Python script wasn't run
            pool = is_vip ? RoguelikeExtraction::DYNAMIC_VIPS : RoguelikeExtraction::DYNAMIC_TRAINERS

            # Filter fought trainers natively inside the spawner
            available = pool.reject { |t| RoguelikeExtraction.fought_trainers.include?(t) }
            available = pool if available.empty?

            chosen_trainer = available.sample
          end

          # Store the mapping for this specific event ID
          $PokemonGlobal.instance_variable_set(:@raid_event_trainers, {}) if !$PokemonGlobal.instance_variable_defined?(:@raid_event_trainers) || $PokemonGlobal.instance_variable_get(:@raid_event_trainers).nil?
          $PokemonGlobal.instance_variable_get(:@raid_event_trainers)[event.id] = chosen_trainer

          # Update the overworld graphic. The user confirmed the graphics
          # are prefixed with trainer_ e.g., 'trainer_YOUNGSTER.png'
          trainer_type = chosen_trainer[0]
          graphic_name = "trainer_#{trainer_type.to_s}"

          # The engine natively calls `event.refresh` repeatedly during map load.
          # If we try to inject a MoveRoute or temporarily change `character_name`,
          # the engine will just read the Editor graphic (e.g. NPC 20) and wipe it.
          # To fix this, we permanently overwrite the event's actual page data in memory.
          rpg_event = event.instance_variable_get(:@event)
          if rpg_event && rpg_event.pages
            rpg_event.pages.each do |page|
              if page.graphic
                page.graphic.character_name = graphic_name
                page.graphic.character_hue = 0
              end
            end
          end
        end

        # Tell the event to immediately re-read its (now modified) page data
        event.refresh if event.respond_to?(:refresh)
      end
    end
  end
end

#===============================================================================
# Hooking into Map Generation
#===============================================================================
# Instead of waiting for on_enter_map (which might trigger too late),
# we alias Game_Map.setup to cull our events BEFORE Overworld_RandomDungeons runs,
# and then apply graphics AFTER it runs.
#===============================================================================

class Game_Map
  alias roguelike_extraction_map_setup setup unless method_defined?(:roguelike_extraction_map_setup)

  def setup(map_id)
    # We must load the map data ourselves briefly to see if it's a dungeon
    # so we can cull events BEFORE the underlying RandomDungeon engine fails to place 42 events
    is_dungeon = false
    if GameData::MapMetadata.exists?(map_id)
      metadata = GameData::MapMetadata.get(map_id)
      is_dungeon = metadata.has_flag?("Dungeon")
    end

    # 1. Run the native setup (which triggers Overworld_RandomDungeons and completely overwrites @map and @events)
    roguelike_extraction_map_setup(map_id)

    # 2. Cull the events from the now-loaded $game_map
    if is_dungeon
      events_to_delete = RoguelikeExtraction.cull_excess_events

      # Even if Overworld_RandomDungeons moved them around, we just delete the objects from memory
      if events_to_delete && @events
        events_to_delete.each do |id|
          @events.delete(id)
        end
      end
    end

    # 2. Apply graphics to the remaining events
    if is_dungeon
      RoguelikeExtraction.spawn_dynamic_events
    end
  end
end
